### ISSUE TITLE
No support for security

### ISSUE THREAD

**Issue by orefalo** [fgeller/kt#70]
Can't connect to a SASL_SSL SASL_PLAINTEXT or even PLAINTEXT authenticated cluster

**Comment by arbrick** [comment]
I would like to throw my hat in for ssl support. It would be great if it could be integrated.

**Comment by fgeller** [comment]
@orefalo @arbrick hey guys - thanks for the feedback and sorry for the delay. Do you guys have some recommendations / ideas for the interface or existing examples? Also a sample Kafka config would help that I could test against :) Ideally something I could use for a wurstmeister/kafka image :)

**Comment by orefalo** [comment]
sorry not close to this topic anymore. but there are plenty of examples online around kerberos, plaintext, sasl and ssl. Sincerely.

**Comment by arbrick** [comment]
@fgeller I am specifically interested in the ssl configuration. The wurstmeister/kafka image has a mention of the ssl configuration [here](https://github.com/wurstmeister/kafka-docker#listener-configuration), but it doesn't go into the details of setting it up. I am mainly familear with kafka from a consumer standpoint and don't have a whole lot of experience setting up the brokers. The Kafka documentation tells you [which configs](https://kafka.apache.org/documentation/#brokerconfigs) you need to specify.

**Comment by orefalo** [comment]
Now I am closer than ever... https://github.com/orefalo/docker-kafka-ssl

**Comment by tednaleid** [comment]
I've used this tls branch of a `kt` fork and it has worked out well.  https://github.com/njhartwell/kt/commits/tls  this code expects a single file with the `CERTIFICATE` and `PRIVATE KEY` but the code could be modified to take 2 files in.  It adds a `-tls` flag and a `--clientCert <public & private key>` flags but otherwise works just like the existing `kt` app.  

We've talked on my team about submitting a PR for this but have struggled with how to implement tests that are valid.

**Comment by hongkongkiwi** [comment]
+1 for this feature, it's hard to use in production without this.

**Comment by tsjnsn** [comment]
If you're using JKS you can try my fork: https://github.com/tsjnsn/kt

```bash
# JKS
$ kt consume -verbose -topic test -offsets oldest -keystore keystore.jks -keypass somepassword -keyalias clientCertAlias -caalias authorityAlias -brokers broker1:9092

# PEM
$ kt consume -verbose -topic test -offsets oldest -key keystore.pem -cert ca.crt -brokers broker1:9092
```

Still needs some work before a PR though

**Comment by fgeller** [comment]
linking #86

**Comment by fgeller** [comment]
hey everyone, quick update:

@rwaweber implemented functionality to use TLS to encrypt the connection to brokers, cf #86 and thanks again @rwaweber :)

had some time to read up on the different auth mechanisms that kafka and sarama support and would like to proceed like this: 
1. generally offer support for what sarama supports. afaict, that's TLS certs and optional plaintext passwords. i'd hope that'd cover 80% of use cases and we could look at more special cases in more detail as need be.
2. simplify the way we provide auth details a bit, and make it easier to add more auth mechanisms later on. more specifically:
* add an `-auth` flag to each command that can also be provided via an `KT_AUTH` env var. it'd expect a json encoding of the auth details. i think that'd make it generally easier to keep the auth details in a file and set an environment variable once per session or so rather than adding the flags to each kt invocation. e.g. in the case of TLS the file could look something like this:
```json
{ "type": "TLS", "key": "/path/to/key", "ca": "/path/to/ca", "certificate": "/path/to/cert" }
```

keen to get feedback as always

**Comment by orefalo** [comment]
Hi @fgeller 

Good job!

Really like kt, it's neat.

Unfortunately, In my company, we don't use passwords. 

We use 2 way SSL - IT Security policy!
 there is a cert on each side, signed with the same parent key (kafka limitation as of 6 months ago).

Sincerely,

**Comment by tsjnsn** [comment]
Here's one: https://github.com/tsjnsn/kt/blob/master/consume.go#L346

**Comment by fgeller** [comment]
cheers @tsjnsn ! That looks a lot like what we're doing at the moment thanks to @rwaweber: [setupCerts](https://github.com/fgeller/kt/blob/master/common.go#L155) - besides the key store handling above the line that you link, or am I missing something?

**Comment by orefalo** [comment]
I am afraid I don’t code in Go. I use your tool from the command line ;-)

My stuff is here…
https://github.com/orefalo/docker-kafka-ssl

It generates the keys, stands up a server and has Java and node.js clients.

I guess GO will use a similar configuration to node.js (no Java specific JKS stuff).

Oli

**Comment by fgeller** [comment]
@orefalo fair enough :) should be able read the node.js bits - will give that a go tomorrow, cheers!

**Comment by cmaenner** [comment]
Also another resource on how to build certificates, if you want to test:

## Reference
[How to generate self-signed certificates](https://coreos.com/os/docs/latest/generate-self-signed-certificates.html)

    cfssl print-defaults config > ca-config.json
    cfssl print-defaults csr > ca-csr.json
    cfssl gencert -initca ca-csr.json | cfssljson -bare ca -
    cfssl print-defaults csr > server.json
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=server server.json | cfssljson -bare server

**Comment by ravanscafi** [comment]
It's working like a charm :)

I just wish we could have env vars for those too :+1:

**Comment by fgeller** [comment]
hey all -- it's been a while, sorry again for the delay - i have been a full-time dad for the past 2.5 years and only recently resumed work on my github projects. i've finally gotten around to setting up the system tests such that we have some automated testing for the authentication features and that allowed me to apply the changes i mentioned in the above [comment](https://github.com/fgeller/kt/issues/70#issuecomment-434205203) more confidently. let me know if you run into any trouble by creating an issue with details please. also, if you are looking for a different authentication mechanism, please create a github issue with details - or add a pull request 😉
